version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - C:\Users\joaoe\OneDrive\Desktop\TesteUnicred\teste-unicred:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: teste_db
      MYSQL_USER: testeuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: teste123
    ports:
      - "3306:3306"
